{% set version = "0.5.0" %}

package:
  name: optima
  version: {{ version }}

source:
  url: https://github.com/reaktoro/optima/archive/v{{ version }}.tar.gz
  sha256: 7a93cb9fc98ed6a9c4a841c80579c03f7c1e773944ff5e765dbb7c486c85cc99
  
build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - ccache
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pytest                                 # [build_platform != target_platform]
  host:
    - catch2 =2
    - eigen
    - python
    - numpy
    - eigen
    - pip
    - pybind11
    - pybind11-abi
    - pybind11-stubgen                       # [not arm64 and not aarch64 and not ppc64le]
    - setuptools
    - pytest
    - pytest-xdist
  run:
    - python
    - numpy
    - eigen
test:
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  files:
    - test/
  imports:
    - optima

about:
  home: https://github.com/reaktoro/optima
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.md
  summary: A C++/Python library for linear and non-linear constrained optimization calculations
  
  description: |
    Optima is a general-purpose C++/Python library for solving linear and
    non-linear constrained optimization problems.
    
  doc_url: https://github.com/reaktoro/optima
  dev_url: https://github.com/reaktoro/optima

extra:
  recipe-maintainers:
    - allanleal
